engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    exclude_paths:
      - spec/**/*
  flog:
    enabled: true
    exclude_paths:
      - db/**/*
      - config/**/*
      - spec/**/*
  rubocop:
    enabled: true
    exclude_paths:
      - db/**/*
    channel: rubocop-0-49
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
